### ISSUE TITLE
Implicit dependency on sb-cltl2

### ISSUE THREAD

**Issue by quicklisp** [cbaggers/trivial-macroexpand-all#2]
Hi, the source references sb-cltl2 but does not express a dependency on it in the system. So it doesn't build for me. Can you please make the dep explicit?

**Comment by cbaggers** [comment]
Done, thanks.
Currently I've use #+sbcl in the asd file but this seems sloppy, what is the correct notation for platform specific dependencies?

**Comment by cbaggers** [comment]
Also sorry for not realizing that this repo wasnt in quicklisp, I was sure I had it in there

**Comment by quicklisp** [comment]
I don't know the best way to conditionally include a dependency in ASDF. Read-time seems good enough to me.

**Comment by cbaggers** [comment]
thanks. This'll do then
